export const styles = {
    chatWithMeButton: {
        cursor: 'pointer',
        borderRadius: '50%',
        backgroundImage: `url(images/avatar.jpg)`,
        boxShadow: '0px 0px 16px 6px rgba(0, 0, 0, 0.33)',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center',
        backgroundSize: '84px',
        width: '84px',
        height: '84px',
    },
    avatarHello: {
        position: 'absolute',
        left: 'calc(-100% - 44px - 28px)',
        top: 'calc(50% - 24px)',
        zIndex: '10000',
        boxShadow: '0px 0px 16px 6px rgba(0, 0, 0, 0.33)',
        padding: '12px 12px 12px 16px',
        borderRadius: '24px',
        backgroundColor: '#F8BB16',
        color: 'black',
    },
    supportWindow: {
        position: 'fixed',
        bottom: '116px',
        right: '24px',
        width: '420px',
        height: '530px',
        maxWidth: 'calc(100% - 48px)',
        maxHeight: 'calc(100% - 48px)',
        backgroundColor: 'white',
        borderRadius: '12px',
        border: `2px solid #F8BB16`,
        overflow: 'hidden',
        boxShadow: '0px 0px 16px 6px rgba(0, 0, 0, 0.33)',
    },
    emailFormWindow: {
        width: '100%',
        overflow: 'hidden',
        transition: "all 0.5s ease",
        WebkitTransition: "all 0.5s ease",
        MozTransition: "all 0.5s ease",
    },
    stripe: {
        position: 'relative',
        top: '-45px',
        width: '100%',
        height: '308px',
        backgroundColor: '#F8BB16',
        transform: 'skewY(-12deg)',
    },
    topText: {
        position: 'relative',
        width: '100%',
        top: '15%',
        color: 'white',
        fontSize: '24px',
        fontWeight: '600',
    },
    emailInput: {
        width: '66%',
        textAlign: 'center',
        outline: 'none',
        padding: '12px',
        borderRadius: '12px',
        border: '2px solid #F8BB16',
    },
    bottomText: {
        position: 'absolute',
        width: '100%',
        top: '60%',
        color: '#F8BB16',
        fontSize: '24px',
        fontWeight: '600',
    },
    loadingDiv: {
        position: 'absolute',
        height: '100%',
        width: '100%',
        textAlign: 'center',
        backgroundColor: 'white',
    },
    loadingIcon: {
        color: '#F8BB16',
        position: 'absolute',
        top: 'calc(50% - 51px)',
        left: 'calc(50% - 51px)',
        fontWeight: '600',
    },
    chatEngineWindow: {
        width: '100%',
        backgroundColor: '#fff',
    }
}
